import { nextTestSetup } from 'e2e-utils'

describe('typed-routes-validator', () => {
  const { next } = nextTestSetup({
    files: __dirname,
  })

  // Test that validator.ts file is generated
  it('should generate validator.ts file', async () => {
    // Read the generated validator file
    const validatorContent = await next.readFile('.next/types/validator.ts')

    // Check that the file contains the expected header
    expect(validatorContent).toContain(
      '// This file is generated automatically by Next.js'
    )
    expect(validatorContent).toContain('// Do not edit this file manually')
    expect(validatorContent).toContain(
      '// This file validates that all pages and layouts export the correct types'
    )
  })

  // Test that validator.ts contains expected type definitions
  it('should contain correct type definitions in validator.ts', async () => {
    const validatorContent = await next.readFile('.next/types/validator.ts')

    // Check for required type definitions
    expect(validatorContent).toContain('type PageConfig = {')
    expect(validatorContent).toContain('type LayoutConfig = {')
    expect(validatorContent).toContain('type RouteHandlerConfig = {')
    expect(validatorContent).toContain('type ApiRouteConfig = {')

    // Check for expected config properties
    expect(validatorContent).toContain('default: React.ComponentType<any>')
    expect(validatorContent).toContain(
      "dynamic?: 'auto' | 'force-dynamic' | 'error' | 'force-static'"
    )
    expect(validatorContent).toContain(
      "runtime?: 'nodejs' | 'experimental-edge' | 'edge'"
    )
    expect(validatorContent).toContain('revalidate?: number | false')
  })

  // Test that validator.ts contains validations for all file types
  it('should contain validations for all file types in validator.ts', async () => {
    const validatorContent = await next.readFile('.next/types/validator.ts')

    // Check for app page validation
    expect(validatorContent).toContain('// Validate app/page')
    expect(validatorContent).toContain('../../app/page')
    expect(validatorContent).toContain('handler satisfies PageConfig')

    // Check for pages router validation
    expect(validatorContent).toContain('// Validate pages/about')
    expect(validatorContent).toContain('../../pages/about')

    // Check for API route validation
    expect(validatorContent).toContain('// Validate app/api/test/route')
    expect(validatorContent).toContain('../../app/api/test/route')
    expect(validatorContent).toContain('handler satisfies RouteHandlerConfig')

    // Check for layout validation
    expect(validatorContent).toContain('// Validate app/layout')
    expect(validatorContent).toContain('../../app/layout')
    expect(validatorContent).toContain('handler satisfies LayoutConfig')
  })

  // Test that validator.ts file structure is correct
  it('should have correct file structure in validator.ts', async () => {
    const validatorContent = await next.readFile('.next/types/validator.ts')

    // Check that the file is structured correctly with proper validation blocks
    const validationBlocks = validatorContent.split('// Validate ').length - 1
    expect(validationBlocks).toBe(4) // Should have exactly 4 validation blocks

    // Each validation block should have the correct structure
    expect(validatorContent).toContain('const handler = {} as typeof import(')
    expect(validatorContent).toContain('handler satisfies ')
  })
})
